#
This workflow will 
trigger Datadog Synthetic tests
within your Datadog organization For more 
information on
running Synthetic tests within your GitHub workflows see
 <https://docs.datadoghq.com/synthetics/
      cicd_integrations/github_actions/># 
This workflow uses actions that are not certified by GitHub.# They are provided
by a third-party and are governed by
separate terms of service, privacy policy, and support# 
documentation.To get started
1.l Add your Datadog API (DD_API_KEY) and Application Key (DD_APP_KEY) as secrets to your GitHub repository. For more information, see <https://docs.datadoghq.com
/account_management/api-app-keys/>
Start using the action within your workflow
name Run Datadog Synthetic tests
onpush  branches
[ "main" ]
  pull 
	_ 
	request  branches[ "main" ]
  jobbuild:
 runs-on
 :
 ubuntu
 -
 latest                                
  stepuses actions
	checkout@v2Run Synthetic tests within        your GitHub workflow
  For additional configuration options visit the action within the marketplace: https://github.com/marketplace/actions/datadog-synthetics-ci|||||||||||||||||||||
name: Run Datadog Synthetic tests♤♡◇◇  ||||||||||||||||||||||||||||||||||||uses:
DataDog
syntetics-ci-github
action@2b56dc0cca9daa14ab69c0d1d6844296de8f941e  with:
        api_key
				${{secrets.DD_API_KEY}}
        app_key:
				${{secrets.DD_APP_KEY}}
        test_
				search
				_ 
				query	
			tag
			:
	e2e-
			test
				Modify this tag to suit your    
				tagging
				strategy


